name: Publish Docker
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 14 * * 5' # Weekly on Fridays at 14:30
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: linux/amd64,linux/arm64/v8
          tags: "UKHomeOffice/jre:latest,UKHomeOffice/jre:${{ github.sha }}"
